// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hncdinmoffyzhplpwxok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuY2Rpbm1vZmZ5emhwbHB3eG9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzExMDksImV4cCI6MjA1OTEwNzEwOX0.N7L3c2NXnZU_bhgsu59j08OyQt71MzoXL7m_rKh-KzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);